# Configuration for meteorological data providers
providers:
  sbr:
    username: "user"
    password: "pwd"
    timezone: 'Europe/Rome'
    chunk_size_days: 7  # Size of chunks when fetching data
    latest_window_minutes: 60  # Window for provider-only latest lookup
    cache_data: true # wheter to cache data in database for faster retrieval
  province:
    timezone: "Europe/Rome"
    chunk_size_days: 365
    latest_window_minutes: 60
    cache_data: true
  open-meteo:
    timezone: "UTC"
    chunk_size_days: 365
    locations: 
      bozen: {'lat': 46.498, 'lon': 11.354}

# Database configuration
database:
  path: "sqlite:///database.db"

# API configuration
api:
  default_timezone: 'Europe/Rome'  # Default timezone for naive datetimes in API requests
